### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by hikarujp** [hikarujp/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by hikarujp** [comment]
これから対応いたします。

**Comment by hurettu** [comment]
da63f0d で対応されました

**Comment by hikarujp** [comment]
da63f0d で対応されました。
